### ISSUE TITLE
Module Not Found Error in Mac

### ISSUE THREAD

**Issue by nantha42** [deepmind/meltingpot#1]
I installed by first cloning the repo, then using a venv, I did "sudo pip3 install ." in meltingpot directory.
Got the success message, but in interpreter I get module not found error for importing dmlab2d.  The test command also shows failed.
```
Building wheels for collected packages: dm-meltingpot
Installing collected packages: dm-meltingpot
  Attempting uninstall: dm-meltingpot
    Found existing installation: dm-meltingpot 1.0.0
    Uninstalling dm-meltingpot-1.0.0:
      Successfully uninstalled dm-meltingpot-1.0.0
Successfully installed dm-meltingpot-1.0.0
```

Error message when running the test.
```
======================================================================
ERROR: harvest_finished (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: harvest_finished
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/nantha/Projc/my_projects/Alab/meltingpotrepo/meltingpot/examples/tutorial/harvest/configs/environment/harvest_finished.py", line 17, in <module>
    from meltingpot.python.utils.substrates import shapes
  File "/Users/nantha/Projc/my_projects/Alab/meltingpotrepo/meltingpot/meltingpot/python/__init__.py", line 17, in <module>
    from meltingpot.python import scenario
  File "/Users/nantha/Projc/my_projects/Alab/meltingpotrepo/meltingpot/meltingpot/python/scenario.py", line 25, in <module>
    from meltingpot.python import substrate as substrate_factory
  File "/Users/nantha/Projc/my_projects/Alab/meltingpotrepo/meltingpot/meltingpot/python/substrate.py", line 22, in <module>
    from meltingpot.python.utils.substrates import builder
  File "/Users/nantha/Projc/my_projects/Alab/meltingpotrepo/meltingpot/meltingpot/python/utils/substrates/builder.py", line 26, in <module>
    import dmlab2d
ModuleNotFoundError: No module named 'dmlab2d'
```

**Comment by duenez** [comment]
Hello,

Did you download and install DeepMind Lab2D? You can do that by downloading a release wheel and installing it. e.g.

```
readonly PYTHON_VERSION="$(python3 --version | sed 's/^Python \([0-9]\)\.\([0-9]\+\)\..*$/\1\2/g')"
readonly DMLAB_WHEEL_ROOT='https://github.com/deepmind/lab2d/releases/download/release_candidate_2021-07-13'
readonly DMLAB_WHEEL="${DMLAB_WHEEL_ROOT}/dmlab2d-1.0-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-macosx_10_15_x86_64.whl"
pip install "${DMLAB_WHEEL}"
```

If that fails, you will have to build DMLab2D from source.

Let me know if this worked.
